class ModelProvider:

    def __init__(self, config): ...

    def get_embedding_model(self): ...

    def get_llm(self): ...

    def get_thinking_llm(self): ...

    def get_prompt_template(self): ...
